[package]
name = "futex"
version = "0.1.0"
edition = "2021"
authors = ["Hongyi Chen <3040313336@qq.com>"]
license = "MIT"

[dependencies]
linkme = { version = "0.3", default-features = false }
lazy_static = { version = "1.4.0", features = ["spin_no_std"] }
log = "0.4"
spin = "0.9"
